version: "3.8"

services:
  eureka-server:
    build:
      context: ./eureka-server 
    ports:
      - "8080:8080"
    container_name: eureka-server

  intern-service:
    build:
      context: ./InternManagement-Service
    ports:
      - "8081:8000"  
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8080/eureka/

  training-service:
    build:
      context: ./TrainingsManagement-Service
    ports:
      - "8082:8001"  
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8080/eureka/
